[package]
name = "bigbed"
version = "0.1.0"
authors = ["William Owens <wowens@ufl.edu>"]
edition = "2018"
license = "GPL-3.0"

[dependencies]

[lib]
name = "bigbed"
path = "src/lib.rs"

[[bin]]
name = "rbb"
path = "src/bin.rs"